### ISSUE TITLE
iOS : POD NOT FOUND , pod install issue

### ISSUE THREAD

**Issue by PawanHGS** [devansh-ramen/flutter_screenshot_and_share#1]
When we install PODS, the error is:
 **No podspec found for `screenshot_and_share` in `.symlinks/plugins/screenshot_and_share/iOS**

![Screenshot 2020-04-21 at 3 23 42 AM](https://user-images.githubusercontent.com/63655523/79803468-aa54f080-837f-11ea-8356-f61c409ee626.png)

**Comment by FrederickEngelhardt** [comment]
Same issue.
```

environment:
  sdk: ">=2.2.2 <3.0.0" # 2.2.2 is minimum version for literal support

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.26+2
  http: ^0.12.0+1
  json_serializable: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  screenshot_and_share: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

```
